name: .NET Release Test

on:
  push:
  pull_request:
    branches: ["main"]
    paths:
      - "src/**/*.cs"
      - "src/**/*.csproj"
      - "tests/**/*.cs"
      - "tests/**/*.csproj"
      - ".github/workflows/dotnet.yml"
      - "!benchmarks/**"
      - "!demos/**"
      - "!.gitattributes"
      - "!.gitignore"
      - "!LICENSE"
      - "!README.md"

jobs:
  build:
    name: build-${{matrix.os}}-${{matrix.dotnet-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #windows-latest
        dotnet-version: ["6.0.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
